### ISSUE TITLE
Highlight image in sidebar when hovering over associated map marker

### ISSUE THREAD

**Issue by jflasher** [developmentseed/libra#4]
Not sure if this one is really practical because while we see all the map markers at once, we only see 4-6 images in the sidebar, so the chances that you will see any highlighting is slim.

**Comment by tolomaps** [comment]
Yes, I was thinking the same thing @jflasher. Also, in many (most?) instances, when the user hovers over a map marker, there are multiple images for that same marker. The user can easily filter by simply clicking on the map marker and then they will see only images for that marker.

**Comment by olafveerman** [comment]
Archiving the repo.
